### ISSUE TITLE
Gemsam basklass för *Manager

### ISSUE THREAD

**Issue by ntijoh-daniel-berg** [itggot-erik-wallstrom/webbserverprojekt#2]
exists_with_id, exists_with_* kan vara samma metod för samtliga klasser
dito för find_*, get_all, add, etc

Om subklasserna har koll  på sina fält, datatyper och krav kan allt automagiseras.

Se t.ex Ecto (https://github.com/elixir-ecto/ecto), active record (http://guides.rubyonrails.org/active_record_basics.html) eller datamapper (https://datamapper.org/) för inspiration

**Comment by ErikWallstrom** [comment]
@itggot-daniel-berg : Jag har nu implementerat en basklass (`Manager`) som innehåller all funktionalitet utom `add`-metoden. Den ser annorlunda ut beroende på vilken tabell det handlar om, och är därför lite för specifik för att kunna implementeras i basklassen på ett snyggt sätt enligt mig.
